### ISSUE TITLE
ModalPickerSingle: addButton -> onClick

### ISSUE THREAD

**Issue by killagore** [42BV/ui#103]
Callback now defines return type of `Promise<any>`, but in most cases it is used to navigate away. A more appropriate type should be `void` or configurable.

**Comment by MrHus** [comment]
The types are:

```ts
export type AddButtonCallback<T> = () => Promise<T>;

export interface AddButtonOptions<T> {
  label: string;
  onClick: AddButtonCallback<T>;
}
```

From: https://github.com/42BV/ui/blob/master/src/form/ModalPicker/types.ts

The idea behind the callback returning a Promise of T is that that T will be instantly selected once the promise is resolved. The use case being that you pop op a modal that lets the user add a new T and when the user saves it will be selected in the modal without navigating away.

**Comment by MrHus** [comment]
Here you can see it in action: https://42bv.github.io/ui/storybook/?path=/story/form-modalpicker-modalpickersingle--with-extra-add-button

When clicking the `Create friend` button a user with the name `admin` is added. Although the example skips the part were a form is presented to the user allowing him to create a friend.
