### ISSUE TITLE
`Theming`: further improve themability of components

### ISSUE THREAD

**Issue by jvhoven** [42BV/ui#138]
Taking the `Button` component as an example; sometimes the user wants more control over applying classes to the inner structure. Currently it's only possible to pass classes to the container element through `className`. Perhaps it would be nice to have separate properties e.g.:

```
type classes = {
	buttonClass: 'btn-primary',
	containerClass: 'container-class'
}
```

---

This would be a nice change to be introduced with #57.

**Comment by MrHus** [comment]
Giving each Component's element the possibility for a custom css class is a lot of work. Plus I think allowing for more customisation will make the library more brittle when upgrading in the future. 

Perhaps do this on a case by case basis. An example of this is the `OpenCloseModal`'s `modalBodyClassName` is sometimes uses to add extra padding, or set the background color in some projects.
