### ISSUE TITLE
Better tooltip abstraction

### ISSUE THREAD

**Issue by TimQuist** [42BV/ui#273]
Using the reactstrap tooltip is too much work

**Comment by MrHus** [comment]
The reason it is too much work is because it is really buggy. Keeps crashing when it looses the target which is a CSS selector. Solution is to use another tooltip library instead of react-strap's.

**Comment by TimQuist** [comment]
Created PR: https://github.com/42BV/ui/pull/324

**Comment by MrHus** [comment]
Released in 2.12.0
