### ISSUE TITLE
DangerJS

### ISSUE THREAD

**Issue by MrHus** [42BV/ui#32]
Create dangerjs bot account, currently we use @jvhoven account to let dangerjs create comments. The bot account should only have the rights to comment and do nothing more.

**Comment by jvhoven** [comment]
- [ ] Find replacement for `danger-yarn`, which shows newly introduced packages inside the PR and reminds the creator to update the lock file.

**Comment by MrHus** [comment]
@jvhoven did we do this?

**Comment by jvhoven** [comment]
The only thing left is to find an `npm` version of `danger-yarn`. We could make this a separate issue however.

**Comment by MrHus** [comment]
Removing dangerjs for now because it does not do anything useful and getting it to work with github actions is taking to long.
