### ISSUE TITLE
Textarea is missing property onKeyup

### ISSUE THREAD

**Issue by b-chiarini** [42BV/ui#446]
The textarea component does not yet support the onKeyup property. Hereby the request to add this support.

**Comment by jvhoven** [comment]
Related to #88.

Should probably be along the lines of:

```
interface BaseProps extends TextareaHTMLAttributes<HTMLTextAreaElement> {
 ....
}
```

Or if you want to go the next mile to enable customisation of the underlying textarea component as well: https://github.com/Andarist/react-textarea-autosize/blob/cb07cdd30badf60e48e303e804cde163bf796fdc/src/index.tsx#L1-L22.

**Comment by MrHus** [comment]
I think this is out of scope. You should use a custom textarea instead. If you want the auto grow behaviour use the `react-textarea-autosize` that Textarea also uses.
