### ISSUE TITLE
Remove complex union types

### ISSUE THREAD

**Issue by MrHus** [42BV/ui#501]
### Preface

Currently we have complex types such as these to make sure the developer cannot
make mistakes when properties interact with each other:

```ts
export interface BaseProps {
  /**
   * Optionally the type of button it is, defaults to 'button'.
   *
   * @default button
   */
  type?: 'button' | 'submit' | 'reset';

  /**
   * Optionally the color of the button.
   */
  color?: Color;

  /**
   *  Optional callback for what needs to happen when the button is clicked.
   */
  onClick?: (event: React.MouseEvent<HTMLElement>) => any;

  /**
   * Whether or not the action you are performing is currently in
   * progress. If so a spinner is rendered inside of the button.
   * This behavior is optional and default to `false`.
   *
   * @default false
   */
  inProgress?: boolean;

  /**
   * Optional extra CSS class you want to add to the component.
   * Useful for styling the component.
   */
  className?: string;

  /**
   * Optionally whether the button is disabled
   *
   * Defaults to `false`
   */
  disabled?: boolean;
}

interface WithIconAndText extends BaseProps {
  /**
   * Optionally the Icon you want to use.
   */
  icon: IconType;

  iconPosition?: IconPosition;

  /**
   * Optionally the size of the icon in pixels.
   */
  iconSize?: number;

  /**
   * Optionally the text of the button.
   */
  children: React.ReactNode;

  /**
   * Optionally whether or not to show the button only as an outline.
   */
  outline?: boolean;

  /**
   * Optionally the size of the button.
   *
   * Defaults to 'md'.
   */
  size?: ButtonSize;

  /**
   * Optionally whether or not the button should take the full width
   * available.
   *
   * Defauts to `false`
   */
  fullWidth?: boolean;
}

interface WithIcon extends BaseProps {
  /**
   * The Icon you want to use.
   */
  icon: IconType;

  iconPosition?: IconPosition;

  /**
   * Optionally the size of the icon in pixels.
   */
  iconSize?: number;

  children?: never;
  outline?: never;
  size?: never;
  fullWidth?: never;
}

interface WithText extends BaseProps {
  /**
   * Optionally the text of the button.
   */
  children: React.ReactNode;

  /**
   * Optionally whether or not to show the button only as an outline.
   */
  outline?: boolean;

  /**
   * Optionally the size of the button.
   *
   * Defaults to 'md'.
   */
  size?: ButtonSize;

  /**
   * Optionally whether or not the button should take the full width
   * available.
   *
   * Defauts to `false`
   */
  fullWidth?: boolean;

  icon?: never;
  iconPosition?: never;
}

export type Props = WithIcon | WithText | WithIconAndText;

export default function Button(props: Props) {
```

There are two problems with this approach:

**1. The union types keep growing and are difficult for us as the developers of 42.nl/ui**
The types are very unwieldy for us as library developers to add new features. I tried doing https://github.com/42BV/ui/issues/442 and because of these complex types it was borderline impossible
to get it to work.

The reason was that when a new property is added which creates a new type for a union, the number of unions 
will explode. Because each union will need to know of the new property, and sometimes this needs another new union to fully work.

**2. For our end users the unions do not help in their error messages**
For example: `<Button iconPosition={"right"} />` will result in the following error: 

`Type '{ iconPosition: "right"; }' is not assignable to type '(IntrinsicAttributes & WithIconAndText) | (IntrinsicAttributes & WithIcon) | (IntrinsicAttributes & WithText)'.
  Property 'children' is missing in type '{ iconPosition: "right"; }' but required in type 'WithText'.`

I think the error is not really readable, and causes a lot of head scratching. 

### The solution
Simply define one `Type Props` with a lot of optional fields, and throw the occasional error when things
are really mis configured.

So for example in this case: `<Button iconPosition={"right"} />` we can do either two things:

1. Ignore the iconPosition, since when there is no Icon the user cannot set a position, which is fair.

2. Or throw a Runtime error saying "42.nl/ui: Button: cannot set iconPosition without an icon".

In this case I would go for option 1, because what does the developer expect to happen? The we select an icon for him?
The developer will see the button without any Icon at all and that is fine.

@jvhoven and @gidomanders your thoughts please.

**Comment by gidomanders** [comment]
I think extending interfaces should be avoided as much as possible. It is better to use types instead of interfaces for reasons like you explained above (and more). We have to review all uses of interface to see if they could be replaced by types.

To answer your question, definitely option 1 in most cases (like 95%), when ignoring certain properties doesn't really matter, like the iconPosition for a button. But in some cases, it really breaks the component if none of the "optional" properties are used, like when the button doesn't have an icon nor children. If there's no default path we can follow, I think a runtime error is the only option we have, but we have to review each occurrence individually.

**Comment by jvhoven** [comment]
An interesting approach they use at ANWB is they split the components into multiple components and use a composition component as a means of coupling a bunch of similar components together. For example; they have a `PrimaryButton` oand a `ButtonIcon` but they also export a `Button` component which enables you to switch button type by passing along the `variant` prop. This decouples a lot of the prop type chains we currently have, although at the cost of a major refactoring.

Perhaps this is a solution we can look to in the future?

**Comment by MrHus** [comment]
@jvhoven the approach is interesting indeed.

Once you fill in the type of the button the autocomplete knows 
which props the variant has. The developer will still need to know 
the type however. 

I think this will make people use the direct Component instead of the 
variant. At least I would :P.

We chose to simply create entirely new components instead of making 
one Button, for instance we have the `ConfirmButton`, `SubmitButton` 
and the `TextButton`.

We use the extending types for small variations in the props, but for
components which are the same. Refactoring this would be quite the
breaking change. So I suggest we keep it as is. 

### Extended proposal

But how do we untangle the types? I've done some more digging and 
these are (most cases at least :P) cases:

1. Button: `type Props = WithIcon | WithText | WithIconAndText;`

2. ConfirmButton: `type Props = WithIcon | WithText | WithIconAndText;`

3. FileInput: `type Props = WithoutLabel | WithLabel;`

4. IconPicker: `type Props = WithoutLabel | WithLabel;`

5. ImageUpload `type Props = WithoutLabel | WithLabel;`

6. Input: `type Props = WithoutLabel | WithLabel;`.

7. Addon: `type Props = IconProps | TextProps`;

8. Textarea: `type Props = WithoutLabel | WithLabel;`

9. ModalPickerMultiple: `type Props<T> = WithoutLabel<T> | WithLabel<T> | WithoutLabelButRenderOptions<T> | WithLabelAndRenderOptions<T>`;

10. ModalPickerSingle: `type Props<T> = type Props<T> = WithoutLabel<T> | WithLabel<T> | WithoutLabelButWithRenderOptions<T> | WithLabelAndRenderOptions<T>;`

11. CheckboxMultiple: `type Props<T> = WithoutLabel<T> | WithLabel<T>;`

12. RadioGroup: `type Props<T> = WithoutLabel<T> | WithLabel<T>;`

13: Select: `type Props<T> = WithoutLabel<T> | WithLabel<T>;`

14: TypeaheadMultiple: `type Props<T> = WithoutLabel<T> | WithLabel<T>;`

15: TypeaheadSingle: `type Props<T> = WithoutLabel<T> | WithLabel<T>;`

16. Texteditor: `type Props = WithoutLabel | WithLabel;`

17. Toggle: `type Props = WithoutLabel | WithLabel;`

18. ValuePicker: `type Props<T> = SingleValuePickerWithoutLabel<T> | MultipleValuePickerWithoutLabel<T> | SingleValuePickerWithLabel<T> | MultipleValuePickerWithLabel<T>;`

### Label variant solution

As you can see most are the same making a difference between having
a label and not having a label: `type Props = WithoutLabel | WithLabel;`, 
and the generic variant: `type Props<T> = WithoutLabel<T> | WithLabel<T>;`.

What the label variants does is this:

```ts
interface BaseProps {
  /**
   * The placeholder of the form element.
   */
  placeholder?: string;

  // Loads more props here
}

interface WithoutLabel extends BaseProps {
  id?: string;
  label?: never;
}

interface WithLabel extends BaseProps {
  /**
   * The id of the form element.
   */
  id: string;

  /**
   * The label of the form element.
   */
  label: React.ReactNode;
}

export type Props = WithoutLabel | WithLabel;
```

When there is a `label` require the `id`. This way when clicking on 
the label you activate the form element. My proposal is for these cases 
to make the `id` optional and if it has not been defined generate a 
random `id` each render. This way we make sure that we always have an 
id. This negates the need for this variant.

That leaves us with the following components which are special:

#### Button and ConfirmButton solution:

`Button` and `ConfirmButton` which both do: 
`type Props = WithIcon | WithText | WithIconAndText;`

They both are defined as:

```ts
export interface BaseProps {
  /**
   * Optionally the type of button it is, defaults to 'button'.
   *
   * @default button
   */
  type?: 'button' | 'submit' | 'reset';

  // A lot more props here
}

interface WithIconAndText extends BaseProps {
  /**
   * Optionally the Icon you want to use.
   */
  icon: IconType;

  iconPosition?: IconPosition;

  /**
   * Optionally the size of the icon in pixels.
   */
  iconSize?: number;

  /**
   * Optionally the text of the button.
   */
  children: React.ReactNode;

  /**
   * Optionally whether or not to show the button only as an outline.
   */
  outline?: boolean;

  /**
   * Optionally the size of the button.
   *
   * Defaults to 'md'.
   */
  size?: ButtonSize;

  /**
   * Optionally whether or not the button should take the full width
   * available.
   *
   * Defauts to `false`
   */
  fullWidth?: boolean;
}

interface WithText extends BaseProps {
  /**
   * Optionally the text of the button.
   */
  children: React.ReactNode;

  /**
   * Optionally whether or not to show the button only as an outline.
   */
  outline?: boolean;

  /**
   * Optionally the size of the button.
   *
   * Defaults to 'md'.
   */
  size?: ButtonSize;

  /**
   * Optionally whether or not the button should take the full width
   * available.
   *
   * Defauts to `false`
   */
  fullWidth?: boolean;

  icon?: never;
  iconPosition?: never;
}

// Means only an icon
interface WithIcon extends BaseProps {
  /**
   * The Icon you want to use.
   */
  icon: IconType;

  iconPosition?: IconPosition;

  /**
   * Optionally the size of the icon in pixels.
   */
  iconSize?: number;

  children?: never;
  outline?: never;
  size?: never;
  fullWidth?: never;
}

export type Props = WithIcon | WithText | WithIconAndText;
```

Basically you can render the button as an Icon only or as a text
button which optionally has an Icon. The Icon only variant gives
the most problems. As it limits the component the most. 

These are the properties of `WithIcon` and the solutions:

1. `iconPosition` ignore it when there is no `icon`, I think this fine
    what would the programmer expect when there is no `icon` to position?

2. We can remove the `iconSize` prop for the `size` prop. This would
   be a limitation, but the user can always fallback to using the 
   `Icon` component directly.

3. The `children` does not really matter that much because giving
   it children would make it a button with text and an icon.

4. The `outline` props does not have a solution but I think in this
   case it should be ignored.

5. `size` is now never but we can make all sizes pass along a fixed
   `size` to the `Icon` prop. For example: `md` would be `24` pixels
    etc etc. 

6. `fullWith` when it is in icon only mode display the icon as `d-flex`
   this way it will take the full width. A bit strange but we can 
   get away with it. Then the `iconPosition` will make it go left
   or right.. 

To for the button variants we can ignore `iconPosition` when there 
is no `icon`, what would the developer expect to happen without an icon
anyway?.


#### Addon solution

`Addon` which is defined as:

```ts
interface BaseProps {
  /**
   * Optionally the color of the Addon.
   */
  color?: Color;

  /**
   * The position of the Addon, is it to the right or left
   * of the input.
   */
  position: Position;

  /**
   * Optional extra CSS class you want to add to the component.
   * Useful for styling the component.
   */
  className?: string;

  /**
   * Optional callback for when the addon is clicked.
   */
  onClick?: () => void;
}

interface IconProps extends BaseProps {
  /**
   * The icon to use as the Addon.
   */
  icon: IconType;

  text?: never;
}

interface TextProps extends BaseProps {
  /**
   * The text to use as the Addon.
   */
  text: string;

  icon?: never;
}

export type Props = IconProps | TextProps;
```

My suggestion is to remove the `icon` and `text` property al together
and replace it with a `Children`. Since we do not export the `Addon`
yet we can do this. Also this would not break anything because the
`Icon` does not receive any extra props, because it is used like this:

```ts
<InputGroupAddon className={className} addonType={addonType}>
  {/* Tabindex set to -1 to avoid tabbing through it */}
  <Button
    className={onClick !== undefined ? 'clickable' : 'not-clickable'}
    tabIndex={-1}
    type="button"
    color={buttonColor}
    onClick={onClick}
  >
    {'text' in props ? props.text : <Icon icon={props.icon} />}
  </Button>
</InputGroupAddon>
```

#### ModalPicker* solution:

`ModalPickerMultiple` and `ModalPickerSingle` which both do:

```ts
export type Props<T> =
  | WithoutLabel<T>
  | WithLabel<T>
  | WithoutLabelButWithRenderOptions<T>
  | WithLabelAndRenderOptions<T>;
```

From the type you would expect that something happens when there is
a label but there are no `renderOptions` but this is not the case.
This seems to be a mistake in the code. Changing it to:

```ts
export type Props<T> =
  | WithoutLabel<T>
  | WithLabel<T>;
```

and making `renderOptions` optional in the base Props does not
break anything: no test fail, plus TypeScript is happy.

@gidomanders  and @jvhoven is this an acceptable solution?

**Comment by gidomanders** [comment]
It was a long read, but yes I think that is the best solution. Definitely for the ModalPicker*, why did we even type it that way with the renderOptions? Anyway, your solutions are clear.

**Comment by jvhoven** [comment]
Seems like an excellent middle ground without too much time investment so I'd say it's a proper solution. 

As for the `WithLabel` properties you suggest generating a random id when no id is given. I can't recall exactly but does this not create confusion with `react-final-form`? I'm not sure if it was the `id` property that `react-final-form` labeled the input value as or the `name` property however so maybe you can disregard this paragraph.

Regarding your comment about the `variant` prop solution;

> I think this will make people use the direct Component instead of the
variant. At least I would :P.

This is perfectly fine! The `variant` property is just tremendously useful for somewhat backwards compatible.

**Comment by MrHus** [comment]
@jvhoven I think you are confused with `name` the `id` is not used by final-form:

Here is a list of all props for Field:

https://final-form.org/docs/react-final-form/types/FieldProps#name

But I will test it just to make sure.
