### ISSUE TITLE
DateTimeInput does not validate typed input using isDateAllowed (if specified)

### ISSUE THREAD

**Issue by arjanvlek** [42BV/ui#561]
## Description
If you manually type the date and time in a `DateTimeInput` field, the data is not validated if `isDateAllowed` is specified. 
Therefore, you can type invalid values which will not trigger a validation error on the `Form`.

## Example
In the `range` example on Storybook, it should not be allowed to pick an end date before the start date.
However, if you type an end date before the start date, it will be accepted and no validation error is shown.

See the attached screenshot and photo (can't take screenshot of disabled mouse cursor on Mac).
<img width="1086" alt="Schermafbeelding 2021-03-29 om 10 54 04" src="https://user-images.githubusercontent.com/10106652/112812501-81ec7080-907d-11eb-8c44-6e6145396a10.png">

![datum-tijd](https://user-images.githubusercontent.com/10106652/112812980-00e1a900-907e-11eb-8800-74861289a195.jpg)

## Edit: Workaround
Manually typed input validation can be achieved by adding validators using `isDateBeforeValidator`, `isDateAfterValidator` and `isDateBetweenValidator`. This is shown in the `jarb range` and `jarb range inclusive` examples on Storybook.

It remains confusing that the `range` and `range inclusive` examples don't include these validations and that this is not the default behaviour of the input field.

**Comment by gidomanders** [comment]
The problem as you describe is validation. As the property is described: `Optional Callback which returns whether a date is selectable.`. We do not validate the input, we only disable clickable elements based on `isDateAllowed` to decrease the chances of a user choosing an invalid date. If using the validators works, which is what they're made for, it's not a workaround, it's the way to go.

All I can do is make this more clear in the story.
