### ISSUE TITLE
Feature: `tagName` property

### ISSUE THREAD

**Issue by jvhoven** [42BV/ui#57]
Button does not accept margin through the `mb` classes Bootstrap provides because it's parent element is a `span` which negates the set margin.

An elegant way to resolve this is adding a `tagName` property, which then determines the container element.

**Comment by gidomanders** [comment]
When you add `d-block` class as well, `mb` classes will work, so you don't need to change the tag.

**Comment by MrHus** [comment]
We should do a display: inline-block by default in 3.0.0
