### ISSUE TITLE
Popover default onClickOutside() throws Error

### ISSUE THREAD

**Issue by TimQuist** [42BV/ui#607]
When I was using the Popover component from @42ui there was an issue with the default `onClickOutside()` event on mobile devices.

Error:
`TypeError: Cannot read properties of undefined (reading 'apply') createTippy.ts`

Error would only occur on mobile (also on devtools when selecting one of the mobile viewports).
Error disappeared once I implemented the `isOpen` and `onClickOutside()` properties myself.

**Comment by TimQuist** [comment]
I'll see if I can recreate this in a codesandbox in a bit

**Comment by gidomanders** [comment]
The Popover component was removed when the Tippy library was replaced with rc-tooltip as it became a duplicate of the Tooltip component. The tippy error will also not occur anymore because that library was removed.
