### ISSUE TITLE
Upgrade Bootstrap to v5.1+ and Reactstrap to v9+

### ISSUE THREAD

**Issue by KilledMufasa** [42BV/ui#618]
Hi all, [Bootstrap 5 has been out and stable for 1.5 years now](https://blog.getbootstrap.com/2021/05/05/bootstrap-5/), and it comes with many good stuff, like improved forms, grid support and accordions, RTL, Dart Sass etc. We would like to use some of this new and improved functionality and keep our dependencies up-to-date, but as of right now we can't because @42BV/ui depends on Bootstrap 4 and Reactstrap 8.

We tried the update-anyway-and-see-what-breaks method, by manually installing [Boostrap 5.1](https://getbootstrap.com/docs/5.1/getting-started/introduction/) and [Reactstrap 9](https://reactstrap.github.io/?path=/docs/home-upgrading--page) but we ran into some errors. So far we found the following ones:

```
ERROR in ./node_modules/@42.nl/ui/dist/index.es.js 1320:29-44
export 'InputGroupAddon' (imported as 'InputGroupAddon') was not found in 'reactstrap'
```

```
ERROR in ./node_modules/@42.nl/ui/dist/index.es.js 3018:29-44
export 'InputGroupAddon' (imported as 'InputGroupAddon') was not found in 'reactstrap'
```

See: https://reactstrap.github.io/?path=/docs/home-upgrading--page

And because @42BV/ui uses classes removed in Bootstrap v5, we had to do some creative work to make sure referenced classes were resolved to their new variants (this works):

```
.badge-pill {
  // was replaced by .rounded-pill in v5
  @extend .rounded-pill
}

.badge-primary {
  // was replaced by .bg-primary in v5
  @extend .bg-primary
}
```

But due to the errors above, we're a bit stuck. It would be great if we could upgrade these libraries and make 42BV/ui even better, thx!

\- Joris van der Burgh

**Comment by gidomanders** [comment]
Hi Joris, Reactstrap only has support for bootstrap 5 since last month, and since we pretty strongly depend on Reactstrap, the upgrade was only possible as of lately. We've already added this topic to the agenda, we'll be discussing it in the React Tech Board meeting. Thanks for bringing up the need in your project and I'll keep you posted through this issue!

**Comment by KilledMufasa** [comment]
Hi, thx for the quick response, appreciated! I wasn't aware that Reactstrap's support for Bootstrap was such a recent thing.

It's great to hear that's it's a topic on the agenda. I'm not in the React Tech Board myself, so I can't speak for my colleagues from Vorsen, but I think this is mostly a nice-to-have for us right now - we're not stuck by any means, just updating the deps. 

Thanks in advance for keeping me posted, keep up the good work!
