### ISSUE TITLE
`~` should be removed from `.scss` files imports?

### ISSUE THREAD

**Issue by TimQuist** [42BV/ui#644]
Hi,

According to [`sass-loader` ](https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules) the usage of `~`  is deprecated in scss imports. 

This is causing problems when using [vite](https://github.com/vitejs/vite). (since the `~` is not part of standard scss, vite cannot read this).

It would be nice if the usage of `~` in these imports could be removed in a future version since it seems to be deprecated anyway.

ex: 
```
@import '~bootstrap/scss/bootstrap';
```
should be: 
```
@import 'bootstrap/scss/bootstrap';
```

**Comment by gidomanders** [comment]
When moving dependencies to optionalDependencies, the dependency stylesheet imports were removed as well. The project developers are responsible to add them to their project now, so the tildes are not an issue anymore.
