### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by jvhoven** [42BV/ui#80]
* TypeAheadMultiple
	* - [x] Tags shows weird rendered error icon

* Button (SubmitButton, etc.)
	* - [x] `className` prop is not accepted
	* - [x] icon alignment; the icon is too close to the text

* Toggle
   MOVED TO #233

* Textarea
	* - [ ] Weird responsive sizing; becomes small and then very big when entering large amounts of text

* Select
	* - [x] `is-valid` styling renders double green bottom through a previous `drop-shadow` styling.

* ModalPickerMultiple
	* - [x] Alignment of select button when no items are selected is weird; should act like the ModalPickerSingle

**Comment by MrHus** [comment]
I will do the alignment of the `ModalPickerMultiple` in another PR.

**Comment by MrHus** [comment]
Icon alignment on button is fixed in another PR.
