### ISSUE TITLE
accept default HTML properties

### ISSUE THREAD

**Issue by jvhoven** [42BV/ui#88]
In the case of for example `Input` it would be nice to have the `InnerInput` extended with the default `InputHTMLElement` properties. This enables users of such components to pass `disabled` and other standard HTML properties to the underlying `Input` component.

**Comment by MrHus** [comment]
I'm declaring it out of scope. The reason being that our components are tiny wrappers around input components (sometimes external ones such as the DatePicker and ColorPicker) to make using them in a bootstrap manner easier.  Easier means surrounding them with a FormControl and making it possible to display errors. 

Making them accept more props will make them more complex for this use-case. If the developer wishes total control he / she is advised to simply use the component directly.
